version: '3.2'
services:
    web:
        image: website
        build:
            context: ./
            dockerfile: ./app.docker
        volumes:
            - ./../application:/var/www/html
        ports:
            - "8088:80"
        links:
            - mysql:mysql
            - memcached:memcached
            - redis:redis
    mysql:
        image: mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=password"
            - "MYSQL_DATABASE=docker_db"
            - "MYSQL_USER=jnpl"
            - "MYSQL_PASSWORD=johnpaul"
        ports:
            - "3308:3306"
    memcached:
        image: memcached
        ports:
            - "11218:11211"
    redis:
        image: redis
        ports:
            - "6378:6379"
