version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: ./app.docker
        volumes:
            - ./../application:/var/www/html
        ports:
            - "8181:8181"
        links:
            - database
    database:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: docker_db
        ports:
            - "3308:3308"
