version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: ./app.docker
        volumes:
            - ./../application:/var/www/html
        ports:
            - "8088:8088"
        links:
            - mysql:mysql
            - memcached:memcached
            - redis:redis
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: docker_db
        ports:
            - "3308:3308"
    memcached:
        image: memcached
        ports:
            - "11218:11218"
    redis:
        image: redis:4.0.1
        ports:
          - "6378:6378"
